=== mpalliser/maven-spring_repository/JAXBCotxox/src/main/resources/org/foobarspam/JAXBCotxox/schemas/cotxox.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="https://api.mobipalma.mobi/docs/"
		xmlns:emt="https://api.mobipalma.mobi/docs/" 
		elementFormDefault="unqualified">
    <element name="carrera" type="emt:Carrera"></element> 
    <complexType name="Carrera">
    	<sequence>
    		<element name="tarjetaCredito" type="string"></element>
    		<element name="destino" type="string"></element>
    		<element name="origen" type="string"></element>
    		<element name="distancia" type="double"></element>
    		<element name="conductor" type="emt:Conductor"></element>
    		<element name="costeTotal" type="double"></element>
    		<element name="propina" type="double"></element>
    	</sequence>
    </complexType>
    <complexType name="Conductor">
    	<sequence>
    		<element name="nombre" type="string"></element>
    		<element name="matricula" type="string"></element>
    		<element name="modelo" type="string"></element>
    		<element name="mediaValoracion" type="double"></element>
    		<element name="valoraciones" type="double" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="ocupado" type="boolean"></element>
    	</sequence>
    </complexType>
</schema>

=== mpalliser/maven-spring_repository/JAXBCotxox/src/main/resources/org/foobarspam/JAXBCotxox/schemas/cotxox.xml
<?xml version="1.0" encoding="UTF-8"?>
<emt:carrera xmlns:emt="https://api.mobipalma.mobi/docs/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://api.mobipalma.mobi/docs/ cotxox.xsd">
	<tarjetaCredito>Mastercard</tarjetaCredito>
	<destino>destino</destino>
	<origen>origen</origen>
	<distancia>15.5</distancia>
	<conductor>
		<nombre>Pepe</nombre>
		<matricula>433214JR</matricula>
		<modelo>micra</modelo>
		<mediaValoracion>4</mediaValoracion>
		<valoraciones>3</valoraciones>
		<ocupado>false</ocupado>
	</conductor>
	<costeTotal>50</costeTotal>
	<propina>5</propina>
</emt:carrera>

=== mpalliser/maven-spring_repository/JAXBCotxox/marshalizado.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:carrera xmlns:ns2="https://api.mobipalma.mobi/docs/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://api.mobipalma.mobi/docs/ cotxox.xsd">
    <tarjetaCredito>Mastercard, 44343564434343423</tarjetaCredito>
    <destino>Andratx</destino>
    <origen>Palma</origen>
    <distancia>15.5</distancia>
    <conductor>
        <nombre>Pepe</nombre>
        <matricula>433214JR</matricula>
        <modelo>micra</modelo>
        <mediaValoracion>4.0</mediaValoracion>
        <valoraciones>3.0</valoraciones>
        <ocupado>false</ocupado>
    </conductor>
    <costeTotal>50.0</costeTotal>
    <propina>5.0</propina>
</ns2:carrera>
